-- SQLite dump generated by Cloudflare Workers
-- Note: This is a simulated dump as SQLite is not yet available in workers-rs
-- Generated at: Mon May 19 2025 12:05:36 GMT-0700 (Pacific Daylight Time)

CREATE TABLE messages (
    id INTEGER PRIMARY KEY,
    timestamp INTEGER NOT NULL,
    content TEXT NOT NULL,
    user_id TEXT NOT NULL
);

