name = "showcase"
main = "build/worker/shim.mjs"
compatibility_date = "2023-12-01"
compatibility_flags = ["durable_object_alarms"]

[build]
command = "cargo install -q worker-build && worker-build --release"

[[durable_objects.bindings]]
name = "WebsocketDO"
class_name = "WebsocketDO"

[[migrations]]
tag = "v1"
new_classes = ["WebsocketDO"]