name = "showcase"
main = "build/worker/shim.mjs"
compatibility_date = "2023-12-01"
compatibility_flags = ["durable_object_alarms"]


[build]
command = "cargo install -q worker-build && worker-build --release"
watch_dir = ["templates"]

[observability]
enabled = true

[[durable_objects.bindings]]
name = "WebsocketDO"
class_name = "WebsocketDO"

[[durable_objects.bindings]]
name = "StudyDO"
class_name = "StudyDO"

[[durable_objects.bindings]]
name = "SttDO"
class_name = "SttDO"

[[migrations]]
tag = "v1"
new_classes = ["WebsocketDO"]

[[migrations]]
tag = "v2"
new_classes = ["StudyDO"]

[[migrations]]
tag = "v3"
new_classes = ["SttDO"]

[ai]
binding = "AI"

[assets]
directory = "static"
